# -*- coding: utf-8 -*-
"""unit_conversion_kg

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dnCdPkZhtsujBdKqW3GdJENVorYKEtEZ

This code reproduces Figure 2 in ITRPV-2020, which is the price trend for mono-Si modules between January, 2014 and January, 2020. This code generates a file based on the year specified (20 means 2020) and generates a file with the data for Table S1 for download that can be used with the pvmontecarlo file.

Read in libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import os
from google.colab import files

import importlib.util

from matplotlib.colors import TwoSlopeNorm

repo_name = "PV-Solar-Recycling"
repo_url = "https://github.com/rmahjabin/PV-Solar-Recycling.git"

if os.path.basename(os.getcwd()) == repo_name:
  os.chdir("/content")

if os.path.exists(repo_name):
  !rm -rf {repo_name}

!git clone {repo_url}
os.chdir(repo_name)

from unit_conversion import convert_dataframe_units
from unit_conversion import build_conversion_matrix

"""Read in the .csv file"""

def convert_usd_per_watt_to_kg(usd_per_watt, conversion_matrix):
    watts_per_kg = conversion_matrix.at['kg', 'Wp']
    usd_per_kg = usd_per_watts * watts_per_kg
    return usd_per_kg

year = 2020
conversion_matrix = build_conversion_matrix(year)
usd_per_watts = 0.274

usd_per_kg = convert_usd_per_watt_to_kg(usd_per_watt, conversion_matrix)
print(f"USD per kg = {usd_per_kg:.4f}")

